@uri=http://localhost:3000

###
GET {{uri}}/cats

###
GET {{uri}}/cats/3

###
POST {{uri}}/cats
content-type: application/json

{
  "name": "111",
  "age": 16,
  "breed": "222"
}

###
PUT {{uri}}/cats/2

###
Get {{uri}}/docs?5